# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectVersion: '1.0.4'

steps:

- task: PowerShell@2
  displayName: 'Check if version was incremented'
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)\scripts\CheckVersion.ps1
    arguments: '-projectVersion "$(projectVersion)"'


- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    version: 6.x

# Build the project
- task: DotNetCoreCLI@2
  displayName: "Build PizzaApi project"
  inputs:
    projects: '$(Build.SourcesDirectory)\PizzaApi.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-incremental'

- task: NugetCommand@2
  displayName: 'Pack the project for nuget release'
  inputs:
    command: custom
    arguments: 'pack $(Build.SourcesDirectory)\PizzaApi.csproj -NonInteractive -OutputDirectory $(Build.ArtifactStagingDirectory)\Nuget -Properties Configuration=$(BuildConfiguration) -Verbosity Detailed -Symbols -SymbolPackageFormat snupkg'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact - Nuget Package'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)\Nuget'
    ArtifactName: Nuget

- task: NugetCommand@2
  displayName: 'Push Build Artifact to Nuget'
  inputs:
    command: push
    packagesToPublish: '$(Build.ArtifactStagingDirectory)\Nuget\*.nupkg'
    nugetFeedType: external
    publishFeedCredentials: 'my-nuget-connection'

- task: GithubRelease@1
  displayName: 'Create Github Release (v$(Build.BuildNumber)-$(Build.BuildId))'
  inputs:
    githubConnection: 'danielmbaluka'
    title: 'PizzaAPI - v$(Build.BuildNumber)'
    tagSource: userSpecifiedTag
    tag: 'v$(Build.BuildNumber)'
