# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)/scripts/CheckVersion.ps1
  displayName: 'Check if version was incremented'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NugetCommand@2
  displayName: 'Pack the project for nuget release'
  inputs:
    command: custom
    arguments: 'pack $(Build.SourcesDirectory)\PizzaApi.csproj -NonInteractive -OutputDirectory $(Build.ArtifactStagingDirectory)\Nuget -Properties Configuration=$(BuildConfiguration) -Verbosity Detailed -Symbols -SymbolPackageFormat snupkg'

- task: GithubRelease@1
  displayName: 'Create Github Release (v$(Build.BuildNumber)-$(Build.BuildId))'
  inputs:
    githubConnection: 'danielmbaluka'
    title: 'PizzaAPI - v$(Build.BuildNumber)'
    tagSource: userSpecifiedTag
    tag: 'v$(Build.BuildNumber)'
